/**
 * Clocked cookbook K1–K12. CLOCK terminals auto-tick (period 2 unless
 * `period` set); IN terminals take held scalars or per-tick programs.
 * Probes are OUTPUT terminals. Waveforms below assume the period-2 clock
 * (edges on odd ticks) and were verified against src/clocked.js.
 */
export const LEVELS_CLOCKED = [
  { id: "k-blink", mode: "clocked", chapter: "Clocked", name: "Blink", tag: "Time base",
    briefing: "Nothing to build: run 8 ticks and watch the CLK lane. Edges land on odd ticks — every divider below keys off them.",
    allowed: {}, par: 0, inputs: [], clocks: ["CLK"], probes: ["CLK"], ticks: 8,
    tests: [{ in: {}, expect: { CLK: [0, 1, 0, 1, 0, 1, 0, 1] } }] },
  { id: "k-delay", mode: "clocked", chapter: "Clocked", name: "Delay Line", tag: "Shift",
    briefing: "Send one pulse through two DELAYs: out[t] = in[t−2]. Program D = 1,0,0,0,0,0,0,0 and read Y.",
    allowed: { DELAY: 2 }, par: 2, inputs: ["D"], clocks: ["CLK"], probes: ["Y"], ticks: 8,
    tests: [{ in: { D: [1, 0, 0, 0, 0, 0, 0, 0] }, expect: { Y: [0, 0, 1, 0, 0, 0, 0, 0] } }] },
  { id: "k-dcap", mode: "clocked", chapter: "Clocked", name: "D Capture", tag: "Sample",
    briefing: "A DFF samples D onto Q at every rising edge. Hold D=1: Q lags one tick behind, then tracks.",
    allowed: { DFF: 1 }, par: 1, inputs: ["D"], clocks: ["CLK"], probes: ["Q"], ticks: 8,
    tests: [{ in: { D: 1 }, expect: { Q: [0, 1, 1, 1, 1, 1, 1, 1] } }] },
  { id: "k-div2", mode: "clocked", chapter: "Clocked", name: "Divide by 2", tag: "Divider",
    briefing: "A T flop with T tied HIGH toggles every edge: the fundamental divider. Toggle input HI to 1 and leave it as your logic-high.",
    allowed: { TFF: 1 }, par: 1, inputs: ["HI"], clocks: ["CLK"], probes: ["Q"], ticks: 8,
    tests: [{ in: { HI: 1 }, expect: { Q: [0, 1, 1, 0, 0, 1, 1, 0] } }] },
  { id: "k-div4", mode: "clocked", chapter: "Clocked", name: "Divide by 4", tag: "Ripple",
    briefing: "Clock a second T flop from Q0's falling edge (wire Q0b — Qb rises exactly when Q0 falls). Two stages, ÷4.",
    allowed: { TFF: 2 }, par: 2, inputs: ["HI"], clocks: ["CLK"], probes: ["Q0", "Q1"], ticks: 8,
    tests: [{ in: { HI: 1 }, expect: {
      Q0: [0, 1, 1, 0, 0, 1, 1, 0],
      Q1: [0, 0, 0, 0, 1, 1, 1, 1],
    } }] },
  { id: "k-count3", mode: "clocked", chapter: "Clocked", name: "3-bit Counter", tag: "Synchronous",
    briefing: "Synchronous trick: every flop shares CLK; T0=HI, T1=Q0, T2=Q0∧Q1 (one AND). Each count held 2 ticks — read the staircase.",
    allowed: { TFF: 3, AND: 1 }, par: 4, inputs: ["HI"], clocks: ["CLK"], probes: ["Q2", "Q1", "Q0"], ticks: 16,
    tests: [{ in: { HI: 1 }, expect: {
      Q0: [0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0],
      Q1: [0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0],
      Q2: [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
    } }] },
  { id: "k-shift", mode: "clocked", chapter: "Clocked", name: "Shift Register", tag: "Serial",
    briefing: "Three DFFs in a chain share one clock: program 0,1,0,1 into D and watch each stage hand its bit down the line (edges sample odd ticks).",
    allowed: { DFF: 3 }, par: 3, inputs: ["D"], clocks: ["CLK"], probes: ["Q0", "Q1", "Q2"], ticks: 8,
    tests: [{ in: { D: [0, 1, 0, 1, 0, 0, 0, 0] }, expect: {
      Q0: [0, 1, 1, 1, 1, 0, 0, 0],
      Q1: [0, 0, 0, 1, 1, 1, 1, 0],
      Q2: [0, 0, 0, 0, 0, 1, 1, 1],
    } }] },
  { id: "k-latch", mode: "clocked", chapter: "Clocked", name: "Gated Latch", tag: "Level",
    briefing: "A DLATCH is transparent while EN=1 and frozen while EN=0. With D=0,1,0,0,0 and EN=1,1,0,0,1 the output must hold 1 through the closed window.",
    allowed: { DLATCH: 1 }, par: 1, inputs: ["D", "EN"], clocks: ["CLK"], probes: ["Y"], ticks: 5,
    tests: [{ in: { D: [0, 1, 0, 0, 0], EN: [1, 1, 0, 0, 1] }, expect: { Y: [0, 1, 1, 1, 0] } }] },
  { id: "k-div3", mode: "clocked", chapter: "Clocked", name: "Divide by 3", tag: "Reset",
    briefing: "Synchronous ÷3: two T flops (T0=HI, T1=Q0) plus an AND watching for 11 that jams async reset. Counts 00,01,01,10,10,00…",
    allowed: { TFF: 2, AND: 1 }, par: 3, inputs: ["HI"], clocks: ["CLK"], probes: ["Q1", "Q0"], ticks: 8,
    tests: [{ in: { HI: 1 }, expect: {
      Q0: [0, 1, 1, 0, 0, 0, 0, 1],
      Q1: [0, 0, 0, 1, 1, 0, 0, 0],
    } }] },
  { id: "k-div5", mode: "clocked", chapter: "Clocked", name: "Divide by 5", tag: "Reset",
    briefing: "Synchronous 3-bit counter (T2=Q0∧Q1) with reset wired to spot 101. Five states then home — decade style.",
    allowed: { TFF: 3, AND: 2 }, par: 5, inputs: ["HI"], clocks: ["CLK"], probes: ["Q2", "Q1", "Q0"], ticks: 16,
    tests: [{ in: { HI: 1 }, expect: {
      Q0: [0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1],
      Q1: [0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1],
      Q2: [0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
    } }] },
  { id: "k-johnson", mode: "clocked", chapter: "Clocked", name: "Johnson Counter", tag: "Ring",
    briefing: "Twisted ring: D0=¬Q2, D1=Q0, D2=Q1. Six states per lap, ÷6 — each flop output is a clean phase.",
    allowed: { DFF: 3, NOT: 1 }, par: 4, inputs: [], clocks: ["CLK"], probes: ["Q2", "Q1", "Q0"], ticks: 8,
    tests: [{ in: {}, expect: {
      Q0: [0, 1, 1, 1, 1, 1, 1, 0],
      Q1: [0, 0, 0, 1, 1, 1, 1, 1],
      Q2: [0, 0, 0, 0, 0, 1, 1, 1],
    } }] },
  { id: "k-pwm", mode: "clocked", chapter: "Clocked", name: "PWM Generator", tag: "Capstone",
    briefing: "Capstone: a synchronous 2-bit counter plus compare logic so OUT=1 while count < duty (D1D0). Shown: duty 2 (50% — high at counts 0 and 1).",
    allowed: { TFF: 2, NOT: 2, AND: 3, OR: 1, XNOR: 1 }, par: 9,
    inputs: ["HI", "D1", "D0"], clocks: ["CLK"], probes: ["OUT"], ticks: 8,
    tests: [{ in: { HI: 1, D1: 1, D0: 0 }, expect: { OUT: [1, 1, 1, 0, 0, 0, 0, 1] } }] },
];
