/**
 * CMOS Lab catalogue C1–C12. Rails (VDD/GND), IN switches and PROBE lamps
 * are free bench infrastructure; `allowed` budgets only the parts in
 * CMOS_PARTS. Tests are { in, out } vectors; C12 is stateful (see cmos.js).
 */
export const LEVELS_CMOS = [
  { id: "c-power", mode: "cmos", chapter: "CMOS Lab", name: "Power It Up", tag: "Rails",
    briefing: "The bench has power rails: wire VDD to lamp P1 (lights 1) and GND to lamp P2 (dark 0). No inputs on this one.",
    allowed: {}, par: 0, inputs: [], probes: ["P1", "P2"],
    tests: [{ in: [], out: [1, 0] }] },
  { id: "c-nmos", mode: "cmos", chapter: "CMOS Lab", name: "NMOS Switch", tag: "Transistor",
    briefing: "An NMOS connects its two ends only when the gate is 1. Wire VDD through the NMOS to Y, and wire a resistor from Y down to GND so Y reads 0 when the switch is open (else it floats!).",
    allowed: { NMOS: 1, RESISTOR: 1 }, par: 2, inputs: ["A"], probes: ["Y"],
    tests: [{ in: [0], out: [0] }, { in: [1], out: [1] }] },
  { id: "c-pmos", mode: "cmos", chapter: "CMOS Lab", name: "PMOS Switch", tag: "Transistor",
    briefing: "A PMOS is the mirror: it connects only when the gate is 0. Wire VDD through the PMOS to Y, with a resistor from Y down to GND. Expect Y=1 exactly when A=0.",
    allowed: { PMOS: 1, RESISTOR: 1 }, par: 2, inputs: ["A"], probes: ["Y"],
    tests: [{ in: [0], out: [1] }, { in: [1], out: [0] }] },
  { id: "c-rtl", mode: "cmos", chapter: "CMOS Lab", name: "Resistor Inverter", tag: "RTL",
    briefing: "Pull Y up to VDD through a resistor, then drag it down with an NMOS gated by A. Y=¬A — and see what happens if you leave the resistor's top end dangling (FLOAT!).",
    allowed: { NMOS: 1, RESISTOR: 1 }, par: 2, inputs: ["A"], probes: ["Y"],
    tests: [{ in: [0], out: [1] }, { in: [1], out: [0] }] },
  { id: "c-inv", mode: "cmos", chapter: "CMOS Lab", name: "CMOS Inverter", tag: "Classic",
    briefing: "The 2-transistor classic: PMOS pulls Y to VDD when A=0, NMOS pulls Y to GND when A=1. No resistor needed — one side is always driving.",
    allowed: { NMOS: 1, PMOS: 1 }, par: 2, inputs: ["A"], probes: ["Y"],
    tests: [{ in: [0], out: [1] }, { in: [1], out: [0] }] },
  { id: "c-nand", mode: "cmos", chapter: "CMOS Lab", name: "CMOS NAND", tag: "Classic",
    briefing: "4 transistors: two PMOS in parallel to VDD (either can pull up), two NMOS in series to GND (both must pull down).",
    allowed: { NMOS: 2, PMOS: 2 }, par: 4, inputs: ["A", "B"], probes: ["Y"],
    tests: [{ in: [0, 0], out: [1] }, { in: [0, 1], out: [1] }, { in: [1, 0], out: [1] }, { in: [1, 1], out: [0] }] },
  { id: "c-nor", mode: "cmos", chapter: "CMOS Lab", name: "CMOS NOR", tag: "Classic",
    briefing: "Dual of NAND: two PMOS in series to VDD, two NMOS in parallel to GND.",
    allowed: { NMOS: 2, PMOS: 2 }, par: 4, inputs: ["A", "B"], probes: ["Y"],
    tests: [{ in: [0, 0], out: [1] }, { in: [0, 1], out: [0] }, { in: [1, 0], out: [0] }, { in: [1, 1], out: [0] }] },
  { id: "c-and", mode: "cmos", chapter: "CMOS Lab", name: "AND from NAND+INV", tag: "Compose",
    briefing: "You know the pattern from gates: NAND (4T) then an inverter (2T). Six transistors, one AND.",
    allowed: { NMOS: 3, PMOS: 3 }, par: 6, inputs: ["A", "B"], probes: ["Y"],
    tests: [{ in: [0, 0], out: [0] }, { in: [0, 1], out: [0] }, { in: [1, 0], out: [0] }, { in: [1, 1], out: [1] }] },
  { id: "c-diode", mode: "cmos", chapter: "CMOS Lab", name: "Diode AND", tag: "History",
    briefing: "Before transistors did logic: two diodes with cathodes on A,B, output pulled up to VDD through a resistor. Any low input drags Y down. Y=A∧B with zero transistors.",
    allowed: { DIODE: 2, RESISTOR: 1 }, par: 3, inputs: ["A", "B"], probes: ["Y"],
    tests: [{ in: [0, 0], out: [0] }, { in: [0, 1], out: [0] }, { in: [1, 0], out: [0] }, { in: [1, 1], out: [1] }] },
  { id: "c-dtl", mode: "cmos", chapter: "CMOS Lab", name: "DTL NAND", tag: "History",
    briefing: "Diode-transistor logic, the 1960s: diode AND (output node pulled to VDD through a resistor) into an NPN inverter (collector pulled to VDD through a second resistor, emitter to GND).",
    allowed: { DIODE: 2, NPN: 1, RESISTOR: 2 }, par: 5, inputs: ["A", "B"], probes: ["Y"],
    tests: [{ in: [0, 0], out: [1] }, { in: [0, 1], out: [1] }, { in: [1, 0], out: [1] }, { in: [1, 1], out: [0] }] },
  { id: "c-tgate", mode: "cmos", chapter: "CMOS Lab", name: "Transmission Gate", tag: "Switch",
    briefing: "NMOS + PMOS in parallel pass A through when S=1 (PMOS needs ¬S — build the inverter too). Checked in the ON state only: an open gate floats!",
    allowed: { NMOS: 2, PMOS: 2 }, par: 4, inputs: ["A", "S"], probes: ["Y"],
    tests: [{ in: [0, 1], out: [0] }, { in: [1, 1], out: [1] }] },
  { id: "c-sr", mode: "cmos", chapter: "CMOS Lab", name: "SR Latch", tag: "Memory",
    briefing: "Two cross-coupled CMOS NORs (8T): Q=¬(R∨Qb), Qb=¬(S∨Q). Set, hold, reset, hold — the first circuit that remembers. Vectors run in order with state carried.",
    allowed: { NMOS: 4, PMOS: 4 }, par: 8, inputs: ["S", "R"], probes: ["Q", "Qb"],
    stateful: true,
    tests: [
      { in: [1, 0], out: [1, 0], fresh: true },
      { in: [0, 0], out: [1, 0] },
      { in: [0, 1], out: [0, 1], fresh: true },
      { in: [0, 0], out: [0, 1] },
    ] },
];
