/**
 * Pack 2 catalogue: N01–N100. Truth tables generated from spec functions
 * (exhaustive up to 5 inputs; `sampled`/`custom-10` lists where noted).
 * Debug Ward levels (N91+) carry `prefill` — nodes/wires placed on the
 * bench at load; keys in0.., out0.., g0... (see app.js loadLevel).
 */
import { buildTests } from "./engine.js";

const CH = {
  fluency: "Fluency",
  nand: "NAND Workshop",
  nor: "NOR Workshop",
  demorgan: "De Morgan & Parity",
  stories: "Everyday Logic",
  routing: "Routing",
  arith: "Arithmetic",
  codes: "Codes & Detectors",
  seg7: "Seven Segments",
  debug: "Debug Ward",
};

// ---------- shared spec helpers ----------
const maj3 = ([a, b, c]) => [(a + b + c >= 2 ? 1 : 0)];
const xor3fn = ([a, b, c]) => [a ^ b ^ c];
const fullsub = ([a, b, bin]) => {
  const s = a ^ b ^ bin;
  const bout = ((1 - a) & b) | ((1 - (a ^ b)) & bin);
  return [s, bout];
};
const add3fn = (vec) => {
  const [a2, a1, a0, b2, b1, b0] = vec;
  const a = (a2 << 2) | (a1 << 1) | a0;
  const b = (b2 << 2) | (b1 << 1) | b0;
  const s = a + b;
  return [(s >> 2) & 1, (s >> 1) & 1, s & 1, (s >> 3) & 1];
};
const ADD3_VECTORS = [
  [0, 0], [7, 0], [0, 7], [7, 7], [7, 1], [1, 7], [3, 5], [5, 3],
  [4, 4], [2, 6], [6, 2], [1, 1], [2, 3], [5, 5], [0, 5], [5, 0],
  [6, 7], [7, 6], [3, 3], [4, 1], [1, 4], [2, 2], [6, 6], [3, 7],
].map(([a, b]) => {
  const inp = [(a >> 2) & 1, (a >> 1) & 1, a & 1, (b >> 2) & 1, (b >> 1) & 1, b & 1];
  return { in: inp, out: add3fn(inp) };
});
const mux41fn = ([A, B, C, D, S1, S0]) => [[A, B, C, D][(S1 << 1) | S0]];
const MUX41_VECTORS = [];
for (const [S1, S0] of [[0, 0], [0, 1], [1, 0], [1, 1]]) {
  const sel = (S1 << 1) | S0;
  for (const data of [[0, 0, 0, 0], [1, 1, 1, 1], [1, 0, 1, 0], [0, 1, 0, 1], [0, 0, 1, 0]]) {
    const inp = [...data, S1, S0];
    void sel;
    MUX41_VECTORS.push({ in: inp, out: mux41fn(inp) });
  }
}
// 7-seg covers from Quine-McCluskey (don't-cares 10-15), verified 0-9.
// Format: [[[var, polarity]]] with polarity 1 = true, 0 = complemented.
const SEG_ON = {
  a: [0, 2, 3, 5, 6, 7, 8, 9],
  b: [0, 1, 2, 3, 4, 7, 8, 9],
  c: [0, 1, 3, 4, 5, 6, 7, 8, 9],
  d: [0, 2, 3, 5, 6, 8, 9],
  e: [0, 2, 6, 8],
  f: [0, 4, 5, 6, 8, 9],
  g: [2, 3, 4, 5, 6, 8, 9],
};
const SEG_COVER = {
  a: [[["x", 0], ["z", 0]], [["y", 1]], [["x", 1], ["z", 1]], [["w", 1]]],
  b: [[["x", 0]], [["y", 0], ["z", 0]], [["y", 1], ["z", 1]]],
  c: [[["y", 0]], [["z", 1]], [["x", 1]]],
  d: [[["x", 0], ["z", 0]], [["x", 0], ["y", 1]], [["x", 1], ["y", 0], ["z", 1]], [["y", 1], ["z", 0]], [["w", 1]]],
  e: [[["x", 0], ["z", 0]], [["y", 1], ["z", 0]]],
  f: [[["y", 0], ["z", 0]], [["x", 1], ["y", 0]], [["x", 1], ["z", 0]], [["w", 1]]],
  g: [[["x", 0], ["y", 1]], [["x", 1], ["y", 0]], [["w", 1]], [["y", 1], ["z", 0]]],
};
function segEntry(seg, allowed, par) {
  const tests = [];
  for (let d = 0; d <= 9; d++) {
    const inp = [(d >> 3) & 1, (d >> 2) & 1, (d >> 1) & 1, d & 1];
    tests.push({ in: inp, out: [SEG_ON[seg].includes(d) ? 1 : 0] });
  }
  return tests;
}

export const LEVELS_PACK2 = [
  // ================= A. Fluency (N01–N12) =================
  { id: "nand1", chapter: CH.fluency, name: "Meet NAND", tag: "Place it",
    briefing: "Y = ¬(A∧B). Place one NAND gate and wire A, B → NAND → Y.",
    allowed: { NAND: 1 }, par: 1, inputs: ["A", "B"], outputs: ["Y"],
    tests: buildTests(2, ([a, b]) => [(a & b ? 0 : 1)]) },
  { id: "nor1", chapter: CH.fluency, name: "Meet NOR", tag: "Place it",
    briefing: "Y = ¬(A∨B). Place one NOR gate and wire it up.",
    allowed: { NOR: 1 }, par: 1, inputs: ["A", "B"], outputs: ["Y"],
    tests: buildTests(2, ([a, b]) => [(a | b ? 0 : 1)]) },
  { id: "xor1", chapter: CH.fluency, name: "Meet XOR", tag: "Place it",
    briefing: "Y = A⊕B (1 when inputs differ). Place one XOR gate.",
    allowed: { XOR: 1 }, par: 1, inputs: ["A", "B"], outputs: ["Y"],
    tests: buildTests(2, ([a, b]) => [a ^ b]) },
  { id: "xnor1", chapter: CH.fluency, name: "Meet XNOR", tag: "Place it",
    briefing: "Y = 1 when A equals B. Place one XNOR gate.",
    allowed: { XNOR: 1 }, par: 1, inputs: ["A", "B"], outputs: ["Y"],
    tests: buildTests(2, ([a, b]) => [(a ^ b ? 0 : 1)]) },
  { id: "and3", chapter: CH.fluency, name: "AND ×3", tag: "Chain",
    briefing: "Y = A∧B∧C from two 2-input ANDs: first AND two inputs, then AND the result with the third.",
    allowed: { AND: 2 }, par: 2, inputs: ["A", "B", "C"], outputs: ["Y"],
    tests: buildTests(3, ([a, b, c]) => [a & b & c]) },
  { id: "or3", chapter: CH.fluency, name: "OR ×3", tag: "Chain",
    briefing: "Y = A∨B∨C from two 2-input ORs.",
    allowed: { OR: 2 }, par: 2, inputs: ["A", "B", "C"], outputs: ["Y"],
    tests: buildTests(3, ([a, b, c]) => [a | b | c]) },
  { id: "and4", chapter: CH.fluency, name: "AND ×4", tag: "Tree",
    briefing: "4-input AND from three 2-input ANDs.",
    allowed: { AND: 3 }, par: 3, inputs: ["A", "B", "C", "D"], outputs: ["Y"],
    tests: buildTests(4, ([a, b, c, d]) => [a & b & c & d]) },
  { id: "or4", chapter: CH.fluency, name: "OR ×4", tag: "Tree",
    briefing: "4-input OR from three 2-input ORs.",
    allowed: { OR: 3 }, par: 3, inputs: ["A", "B", "C", "D"], outputs: ["Y"],
    tests: buildTests(4, ([a, b, c, d]) => [a | b | c | d]) },
  { id: "and5", chapter: CH.fluency, name: "AND ×5", tag: "Tree",
    briefing: "5-input AND from four 2-input ANDs (32 test cases — take your time).",
    allowed: { AND: 4 }, par: 4, inputs: ["A", "B", "C", "D", "E"], outputs: ["Y"],
    tests: buildTests(5, ([a, b, c, d, e]) => [a & b & c & d & e]) },
  { id: "or5", chapter: CH.fluency, name: "OR ×5", tag: "Tree",
    briefing: "5-input OR from four 2-input ORs.",
    allowed: { OR: 4 }, par: 4, inputs: ["A", "B", "C", "D", "E"], outputs: ["Y"],
    tests: buildTests(5, ([a, b, c, d, e]) => [a | b | c | d | e]) },
  { id: "imply", chapter: CH.fluency, name: "IMPLY", tag: "If-then",
    briefing: "A→B is 0 only when A=1 and B=0. Build ¬A∨B from NOT + OR.",
    allowed: { NOT: 1, OR: 1 }, par: 2, inputs: ["A", "B"], outputs: ["Y"],
    tests: buildTests(2, ([a, b]) => [(a && !b ? 0 : 1)]) },
  { id: "nimply", chapter: CH.fluency, name: "NIMPLY", tag: "But-not",
    briefing: "Y = A∧¬B (A but not B). Build from NOT + AND.",
    allowed: { NOT: 1, AND: 1 }, par: 2, inputs: ["A", "B"], outputs: ["Y"],
    tests: buildTests(2, ([a, b]) => [(a && !b ? 1 : 0)]) },

  // ================= B. NAND workshop (N13–N20) =================
  { id: "not-nand", chapter: CH.nand, name: "NOT from NAND", tag: "Universal",
    briefing: "Tie both NAND inputs to A: Y = A⊼A = ¬A.",
    allowed: { NAND: 1 }, par: 1, inputs: ["A"], outputs: ["Y"],
    tests: buildTests(1, ([a]) => [a ? 0 : 1]) },
  { id: "and-nand", chapter: CH.nand, name: "AND from NAND", tag: "Universal",
    briefing: "AND = NAND followed by NOT-from-NAND (tie the second gate's inputs).",
    allowed: { NAND: 2 }, par: 2, inputs: ["A", "B"], outputs: ["Y"],
    tests: buildTests(2, ([a, b]) => [a & b]) },
  { id: "or-nand", chapter: CH.nand, name: "OR from NAND", tag: "Universal",
    briefing: "A∨B = (¬A)⊼(¬B). Invert both inputs with tied NANDs, then NAND the results.",
    allowed: { NAND: 3 }, par: 3, inputs: ["A", "B"], outputs: ["Y"],
    tests: buildTests(2, ([a, b]) => [a | b]) },
  { id: "xnor-nand", chapter: CH.nand, name: "XNOR from NAND", tag: "Universal",
    briefing: "Build the 4-NAND XOR, then invert its output with a tied NAND.",
    allowed: { NAND: 5 }, par: 5, inputs: ["A", "B"], outputs: ["Y"],
    tests: buildTests(2, ([a, b]) => [(a ^ b ? 0 : 1)]) },
  { id: "mux-nand", chapter: CH.nand, name: "MUX from NAND", tag: "Universal",
    briefing: "2:1 MUX from NANDs only: NOT→1, each AND→2, the OR→3. Inputs A,B,S.",
    allowed: { NAND: 8 }, par: 8, inputs: ["A", "B", "S"], outputs: ["Y"],
    tests: buildTests(3, ([a, b, s]) => [(s ? b : a)]) },
  { id: "demux-nand", chapter: CH.nand, name: "DEMUX from NAND", tag: "Universal",
    briefing: "1:2 DEMUX from NANDs: NOT→1, each AND→2. Inputs D,S.",
    allowed: { NAND: 5 }, par: 5, inputs: ["D", "S"], outputs: ["Y0", "Y1"],
    tests: buildTests(2, ([d, s]) => [(s ? 0 : d), (s ? d : 0)]) },
  { id: "ha-nand", chapter: CH.nand, name: "Half Adder from NAND", tag: "Universal",
    briefing: "Sum via 4-NAND XOR, carry via NAND+NOT. Outputs S,C.",
    allowed: { NAND: 6 }, par: 6, inputs: ["A", "B"], outputs: ["S", "C"],
    tests: buildTests(2, ([a, b]) => [a ^ b, a & b]) },
  { id: "and3-nand", chapter: CH.nand, name: "AND×3 from NAND", tag: "Universal",
    briefing: "3-input AND: NAND+NOT for the first pair (2), NAND+NOT with C (2).",
    allowed: { NAND: 4 }, par: 4, inputs: ["A", "B", "C"], outputs: ["Y"],
    tests: buildTests(3, ([a, b, c]) => [a & b & c]) },

  // ================= C. NOR workshop (N21–N27) =================
  { id: "not-nor", chapter: CH.nor, name: "NOT from NOR", tag: "Universal II",
    briefing: "Y = A⊽A. Tie both inputs.",
    allowed: { NOR: 1 }, par: 1, inputs: ["A"], outputs: ["Y"],
    tests: buildTests(1, ([a]) => [a ? 0 : 1]) },
  { id: "or-nor", chapter: CH.nor, name: "OR from NOR", tag: "Universal II",
    briefing: "OR = NOR followed by NOT-from-NOR.",
    allowed: { NOR: 2 }, par: 2, inputs: ["A", "B"], outputs: ["Y"],
    tests: buildTests(2, ([a, b]) => [a | b]) },
  { id: "and-nor", chapter: CH.nor, name: "AND from NOR", tag: "Universal II",
    briefing: "A∧B = (¬A)⊽(¬B). Invert both with tied NORs, then NOR.",
    allowed: { NOR: 3 }, par: 3, inputs: ["A", "B"], outputs: ["Y"],
    tests: buildTests(2, ([a, b]) => [a & b]) },
  { id: "xnor-nor", chapter: CH.nor, name: "XNOR from NOR", tag: "Universal II",
    briefing: "Build the 6-NOR XOR, then a tied-NOR inverter (7 total).",
    allowed: { NOR: 7 }, par: 7, inputs: ["A", "B"], outputs: ["Y"],
    tests: buildTests(2, ([a, b]) => [(a ^ b ? 0 : 1)]) },
  { id: "mux-nor", chapter: CH.nor, name: "MUX from NOR", tag: "Universal II",
    briefing: "2:1 MUX: NOT→1, each AND→3, OR→2. Inputs A,B,S.",
    allowed: { NOR: 9 }, par: 9, inputs: ["A", "B", "S"], outputs: ["Y"],
    tests: buildTests(3, ([a, b, s]) => [(s ? b : a)]) },
  { id: "demux-nor", chapter: CH.nor, name: "DEMUX from NOR", tag: "Universal II",
    briefing: "1:2 DEMUX: NOT→1, each AND→3. Inputs D,S.",
    allowed: { NOR: 7 }, par: 7, inputs: ["D", "S"], outputs: ["Y0", "Y1"],
    tests: buildTests(2, ([d, s]) => [(s ? 0 : d), (s ? d : 0)]) },
  { id: "ha-nor", chapter: CH.nor, name: "Half Adder from NOR", tag: "Universal II",
    briefing: "Sum via 6-NOR XOR, carry via NOR-built AND (3). Outputs S,C.",
    allowed: { NOR: 9 }, par: 9, inputs: ["A", "B"], outputs: ["S", "C"],
    tests: buildTests(2, ([a, b]) => [a ^ b, a & b]) },

  // ================= D. De Morgan & parity (N28–N35) =================
  { id: "or-aoi", chapter: CH.demorgan, name: "OR the De Morgan Way", tag: "Duality",
    briefing: "A∨B = ¬(¬A∧¬B). Two input NOTs, one AND, one output NOT.",
    allowed: { AND: 1, NOT: 3 }, par: 4, inputs: ["A", "B"], outputs: ["Y"],
    tests: buildTests(2, ([a, b]) => [a | b]) },
  { id: "and-oai", chapter: CH.demorgan, name: "AND the De Morgan Way", tag: "Duality",
    briefing: "A∧B = ¬(¬A∨¬B). Two input NOTs, one OR, one output NOT.",
    allowed: { OR: 1, NOT: 3 }, par: 4, inputs: ["A", "B"], outputs: ["Y"],
    tests: buildTests(2, ([a, b]) => [a & b]) },
  { id: "xnor-x", chapter: CH.demorgan, name: "XNOR via XOR", tag: "Remix",
    briefing: "XNOR = NOT after XOR. Short and sweet.",
    allowed: { XOR: 1, NOT: 1 }, par: 2, inputs: ["A", "B"], outputs: ["Y"],
    tests: buildTests(2, ([a, b]) => [(a ^ b ? 0 : 1)]) },
  { id: "xor3", chapter: CH.demorgan, name: "3-way Parity", tag: "Chain",
    briefing: "P = A⊕B⊕C. Chain two XORs.",
    allowed: { XOR: 2 }, par: 2, inputs: ["A", "B", "C"], outputs: ["P"],
    tests: buildTests(3, xor3fn) },
  { id: "xnor3", chapter: CH.demorgan, name: "Evenness of 3", tag: "Chain",
    briefing: "Y = ¬(A⊕B⊕C): 1 when the parity is even. Two XORs + NOT.",
    allowed: { XOR: 2, NOT: 1 }, par: 3, inputs: ["A", "B", "C"], outputs: ["Y"],
    tests: buildTests(3, ([a, b, c]) => [(a ^ b ^ c ? 0 : 1)]) },
  { id: "parity4", chapter: CH.demorgan, name: "Nibble Parity", tag: "Chain",
    briefing: "P = A⊕B⊕C⊕D. Three XORs in a chain.",
    allowed: { XOR: 3 }, par: 3, inputs: ["A", "B", "C", "D"], outputs: ["P"],
    tests: buildTests(4, ([a, b, c, d]) => [a ^ b ^ c ^ d]) },
  { id: "parity5", chapter: CH.demorgan, name: "5-bit Parity", tag: "Chain",
    briefing: "Odd parity over 5 bits. Four XORs (32 test cases).",
    allowed: { XOR: 4 }, par: 4, inputs: ["A", "B", "C", "D", "E"], outputs: ["P"],
    tests: buildTests(5, ([a, b, c, d, e]) => [a ^ b ^ c ^ d ^ e]) },
  { id: "nand5", chapter: CH.demorgan, name: "NAND ×5", tag: "Tree",
    briefing: "5-input NAND = 4-AND tree + output NOT.",
    allowed: { AND: 4, NOT: 1 }, par: 5, inputs: ["A", "B", "C", "D", "E"], outputs: ["Y"],
    tests: buildTests(5, ([a, b, c, d, e]) => [(a & b & c & d & e ? 0 : 1)]) },

  // ================= E. Everyday logic (N36–N50) =================
  { id: "twokey", chapter: CH.stories, name: "Two-Key Launch", tag: "Story",
    briefing: "Launch needs both keys turned: Y = A∧B.",
    allowed: { AND: 1 }, par: 1, inputs: ["A", "B"], outputs: ["Y"],
    tests: buildTests(2, ([a, b]) => [a & b]) },
  { id: "porch", chapter: CH.stories, name: "Porch Light", tag: "Story",
    briefing: "Light is on with motion but not in daylight: Y = M∧¬L.",
    allowed: { AND: 1, NOT: 1 }, par: 2, inputs: ["M", "L"], outputs: ["Y"],
    tests: buildTests(2, ([m, l]) => [(m && !l ? 1 : 0)]) },
  { id: "greenhouse", chapter: CH.stories, name: "Greenhouse Fan", tag: "Story",
    briefing: "Fan runs when (hot AND occupied) OR manual override: Y=(H∧O)∨M.",
    allowed: { AND: 1, OR: 1 }, par: 2, inputs: ["H", "O", "M"], outputs: ["Y"],
    tests: buildTests(3, ([h, o, m]) => [((h && o) || m ? 1 : 0)]) },
  { id: "crosswalk", chapter: CH.stories, name: "Crosswalk", tag: "Story",
    briefing: "Walk sign = button pressed AND no traffic: Y = B∧¬T.",
    allowed: { AND: 1, NOT: 1 }, par: 2, inputs: ["B", "T"], outputs: ["Y"],
    tests: buildTests(2, ([b, t]) => [(b && !t ? 1 : 0)]) },
  { id: "alarm", chapter: CH.stories, name: "Burglar Alarm", tag: "Story",
    briefing: "Alarm sounds when armed AND (door OR window opens).",
    allowed: { AND: 1, OR: 1 }, par: 2, inputs: ["M", "D", "W"], outputs: ["Y"],
    tests: buildTests(3, ([m, d, w]) => [(m && (d || w) ? 1 : 0)]) },
  { id: "sprinkler", chapter: CH.stories, name: "Sprinkler", tag: "Story",
    briefing: "Water when (hot AND dry) OR manual: Y=(H∧D)∨O.",
    allowed: { AND: 1, OR: 1 }, par: 2, inputs: ["H", "D", "O"], outputs: ["Y"],
    tests: buildTests(3, ([h, d, o]) => [((h && d) || o ? 1 : 0)]) },
  { id: "elevator", chapter: CH.stories, name: "Elevator Door", tag: "Story",
    briefing: "Doors open when (at floor AND stopped) OR attendant key: Y=(F∧D)∨A.",
    allowed: { AND: 1, OR: 1 }, par: 2, inputs: ["F", "D", "A"], outputs: ["Y"],
    tests: buildTests(3, ([f, d, a]) => [((f && d) || a ? 1 : 0)]) },
  { id: "museum", chapter: CH.stories, name: "Museum Case", tag: "Story",
    briefing: "Alarm = armed AND (glass OR motion OR pressure). Chain two ORs.",
    allowed: { AND: 1, OR: 2 }, par: 3, inputs: ["M", "G", "O", "P"], outputs: ["Y"],
    tests: buildTests(4, ([m, g, o, p]) => [(m && (g || o || p) ? 1 : 0)]) },
  { id: "sump", chapter: CH.stories, name: "Sump Pump", tag: "Story",
    briefing: "Pump runs when (water high AND NOT in service) OR test switch.",
    allowed: { AND: 1, OR: 1, NOT: 1 }, par: 3, inputs: ["H", "M", "T"], outputs: ["Y"],
    tests: buildTests(3, ([h, m, t]) => [((h && !m) || t ? 1 : 0)]) },
  { id: "coop", chapter: CH.stories, name: "Coop Door", tag: "Story",
    briefing: "Door opens at dawn AND (not raining OR manual): Y=D∧(¬R∨M).",
    allowed: { AND: 1, OR: 1, NOT: 1 }, par: 3, inputs: ["D", "R", "M"], outputs: ["Y"],
    tests: buildTests(3, ([d, r, m]) => [(d && (!r || m) ? 1 : 0)]) },
  { id: "fridge", chapter: CH.stories, name: "Fridge Beep", tag: "Story",
    briefing: "Beep when the door is open AND (it's night OR long open).",
    allowed: { AND: 1, OR: 1 }, par: 2, inputs: ["D", "N", "T"], outputs: ["Y"],
    tests: buildTests(3, ([d, n, t]) => [(d && (n || t) ? 1 : 0)]) },
  { id: "fire", chapter: CH.stories, name: "Fire Panel", tag: "Story",
    briefing: "Alarm = smoke OR (heat AND NOT test mode).",
    allowed: { AND: 1, OR: 1, NOT: 1 }, par: 3, inputs: ["S", "H", "T"], outputs: ["Y"],
    tests: buildTests(3, ([s, h, t]) => [(s || (h && !t) ? 1 : 0)]) },
  { id: "safe", chapter: CH.stories, name: "Safe Lock", tag: "Story",
    briefing: "Opens on code (A AND B) or code (C without B): Y=(A∧B)∨(C∧¬B).",
    allowed: { AND: 3, OR: 1, NOT: 1 }, par: 4, inputs: ["A", "B", "C"], outputs: ["Y"],
    tests: buildTests(3, ([a, b, c]) => [((a && b) || (c && !b) ? 1 : 0)]) },
  { id: "buzz", chapter: CH.stories, name: "Quiz Buzzer", tag: "Story",
    briefing: "Buzz when any contestant (A,B,C) presses AND the host hasn't locked out.",
    allowed: { AND: 1, OR: 2, NOT: 1 }, par: 4, inputs: ["A", "B", "C", "L"], outputs: ["Y"],
    tests: buildTests(4, ([a, b, c, l]) => [((a || b || c) && !l ? 1 : 0)]) },
  { id: "veto", chapter: CH.stories, name: "Veto Vote", tag: "Story",
    briefing: "Motion passes with a 2-of-3 majority AND no veto: reuse the majority pattern, then AND with ¬V.",
    allowed: { AND: 4, OR: 3, NOT: 1 }, par: 7, inputs: ["A", "B", "C", "V"], outputs: ["Y"],
    tests: buildTests(4, ([a, b, c, v]) => [((a + b + c >= 2) && !v ? 1 : 0)]) },

  // ================= F. Routing (N51–N59) =================
  { id: "demux12", chapter: CH.routing, name: "1:2 DEMUX", tag: "Route",
    briefing: "Steer D to Y0 (S=0) or Y1 (S=1): Y0=¬S∧D, Y1=S∧D. Inputs D,S.",
    allowed: { AND: 2, NOT: 1 }, par: 3, inputs: ["D", "S"], outputs: ["Y0", "Y1"],
    tests: buildTests(2, ([d, s]) => [(s ? 0 : d), (s ? d : 0)]) },
  { id: "enc42", chapter: CH.routing, name: "4-to-2 Encoder", tag: "Code",
    briefing: "One-hot I3..I0 to binary: Y1=I3∨I2, Y0=I3∨I1.",
    allowed: { OR: 2 }, par: 2, inputs: ["I3", "I2", "I1", "I0"], outputs: ["Y1", "Y0"],
    tests: buildTests(4, ([i3, i2, i1]) => [(i3 || i2 ? 1 : 0), (i3 || i1 ? 1 : 0)]) },
  { id: "prienc", chapter: CH.routing, name: "Priority Encoder", tag: "Code",
    briefing: "Highest live input wins: Y1=I3∨I2, Y0=I3∨(¬I2∧I1).",
    allowed: { OR: 2, AND: 1, NOT: 1 }, par: 4, inputs: ["I3", "I2", "I1", "I0"], outputs: ["Y1", "Y0"],
    tests: buildTests(4, ([i3, i2, i1]) => [(i3 || i2 ? 1 : 0), ((i3 || (!i2 && i1)) ? 1 : 0)]) },
  { id: "dec24", chapter: CH.routing, name: "2-to-4 Decoder", tag: "Route",
    briefing: "One output HIGH per input code: Yi = minterm i of (A,B). Two NOTs + four ANDs.",
    allowed: { AND: 4, NOT: 2 }, par: 6, inputs: ["A", "B"], outputs: ["Y0", "Y1", "Y2", "Y3"],
    tests: buildTests(2, ([a, b]) => [
      ((!a && !b) ? 1 : 0), ((!a && b) ? 1 : 0), ((a && !b) ? 1 : 0), ((a && b) ? 1 : 0),
    ]) },
  { id: "mux41", chapter: CH.routing, name: "4:1 MUX", tag: "Route",
    briefing: "Pick one of A,B,C,D with S1,S0. Each 3-input AND from two 2-ANDs (8), OR the four terms (3), invert selects (2). Sampled test vectors.",
    allowed: { AND: 8, OR: 3, NOT: 2 }, par: 13,
    inputs: ["A", "B", "C", "D", "S1", "S0"], outputs: ["Y"], tests: MUX41_VECTORS },
  { id: "crossbar", chapter: CH.routing, name: "2×2 Crossbar", tag: "Route",
    briefing: "S=0: straight (Y0=A,Y1=B). S=1: crossed. Two MUXes sharing one NOT: 7 gates.",
    allowed: { AND: 4, OR: 2, NOT: 1 }, par: 7, inputs: ["A", "B", "S"], outputs: ["Y0", "Y1"],
    tests: buildTests(3, ([a, b, s]) => [(s ? b : a), (s ? a : b)]) },
  { id: "aoi", chapter: CH.routing, name: "AND-OR-Invert", tag: "Compound",
    briefing: "Y = ¬((A∧B)∨C). The classic compound gate from 3 parts.",
    allowed: { AND: 1, OR: 1, NOT: 1 }, par: 3, inputs: ["A", "B", "C"], outputs: ["Y"],
    tests: buildTests(3, ([a, b, c]) => [((a && b) || c ? 0 : 1)]) },
  { id: "oai", chapter: CH.routing, name: "OR-AND-Invert", tag: "Compound",
    briefing: "Y = ¬((A∨B)∧C). Mirror of AOI.",
    allowed: { AND: 1, OR: 1, NOT: 1 }, par: 3, inputs: ["A", "B", "C"], outputs: ["Y"],
    tests: buildTests(3, ([a, b, c]) => [((a || b) && c ? 0 : 1)]) },
  { id: "dec24en", chapter: CH.routing, name: "Decoder with Enable", tag: "Route",
    briefing: "2-to-4 decoder gated by E: Yi = E ∧ minterm. Four minterm ANDs + four enable ANDs + two NOTs.",
    allowed: { AND: 8, NOT: 2 }, par: 10, inputs: ["A", "B", "E"], outputs: ["Y0", "Y1", "Y2", "Y3"],
    tests: buildTests(3, ([a, b, e]) => [
      ((e && !a && !b) ? 1 : 0), ((e && !a && b) ? 1 : 0),
      ((e && a && !b) ? 1 : 0), ((e && a && b) ? 1 : 0),
    ]) },

  // ================= G. Arithmetic (N60–N75) =================
  { id: "gt1", chapter: CH.arith, name: "Greater Than (1-bit)", tag: "Compare",
    briefing: "A>B for single bits: Y = A∧¬B.",
    allowed: { AND: 1, NOT: 1 }, par: 2, inputs: ["A", "B"], outputs: ["Y"],
    tests: buildTests(2, ([a, b]) => [(a && !b ? 1 : 0)]) },
  { id: "lt1", chapter: CH.arith, name: "Less Than (1-bit)", tag: "Compare",
    briefing: "A<B for single bits: Y = ¬A∧B.",
    allowed: { AND: 1, NOT: 1 }, par: 2, inputs: ["A", "B"], outputs: ["Y"],
    tests: buildTests(2, ([a, b]) => [(!a && b ? 1 : 0)]) },
  { id: "eq1b", chapter: CH.arith, name: "Equal (1-bit, built)", tag: "Compare",
    briefing: "No XNOR allowed: Y = (A∧B)∨(¬A∧¬B), 5 gates.",
    allowed: { AND: 2, OR: 1, NOT: 2 }, par: 5, inputs: ["A", "B"], outputs: ["Y"],
    tests: buildTests(2, ([a, b]) => [(a === b ? 1 : 0)]) },
  { id: "comp1", chapter: CH.arith, name: "1-bit Comparator", tag: "Compare",
    briefing: "GT, EQ, LT all at once. Place the XNOR for EQ, build GT/LT around it.",
    allowed: { AND: 2, NOT: 2, XNOR: 1 }, par: 5, inputs: ["A", "B"], outputs: ["GT", "EQ", "LT"],
    tests: buildTests(2, ([a, b]) => [(a > b ? 1 : 0), (a === b ? 1 : 0), (a < b ? 1 : 0)]) },
  { id: "ha-noxor", chapter: CH.arith, name: "Half Adder, No XOR", tag: "Add",
    briefing: "Sum via the 5-gate classic XOR, carry via AND.",
    allowed: { AND: 3, OR: 1, NOT: 2 }, par: 6, inputs: ["A", "B"], outputs: ["S", "C"],
    tests: buildTests(2, ([a, b]) => [a ^ b, a & b]) },
  { id: "halfsub", chapter: CH.arith, name: "Half Subtractor", tag: "Subtract",
    briefing: "A−B: difference D=A⊕B, borrow Bout=¬A∧B.",
    allowed: { XOR: 1, AND: 1, NOT: 1 }, par: 3, inputs: ["A", "B"], outputs: ["D", "Bout"],
    tests: buildTests(2, ([a, b]) => [(a ^ b), ((!a && b) ? 1 : 0)]) },
  { id: "fullsub", chapter: CH.arith, name: "Full Subtractor", tag: "Subtract",
    briefing: "A−B−Bin: S=A⊕B⊕Bin, Bout=(¬A∧B)∨(¬(A⊕B)∧Bin). Hint: compute T=A⊕B first.",
    allowed: { XOR: 2, AND: 2, NOT: 2, OR: 1 }, par: 7, inputs: ["A", "B", "Bin"], outputs: ["S", "Bout"],
    tests: buildTests(3, fullsub) },
  { id: "gt2", chapter: CH.arith, name: "2-bit Greater-Than", tag: "Compare",
    briefing: "GT=(a1∧¬b1)∨(¬(a1⊕b1)∧a0∧¬b0). High bits decide; low bits break ties.",
    allowed: { AND: 4, OR: 1, NOT: 3, XOR: 1 }, par: 8,
    inputs: ["a1", "a0", "b1", "b0"], outputs: ["GT"],
    tests: buildTests(4, ([a1, a0, b1, b0]) => [(((a1 << 1) | a0) > ((b1 << 1) | b0) ? 1 : 0)]) },
  { id: "lt2", chapter: CH.arith, name: "2-bit Less-Than", tag: "Compare",
    briefing: "Mirror of greater-than: LT=(¬a1∧b1)∨(¬(a1⊕b1)∧¬a0∧b0).",
    allowed: { AND: 4, OR: 1, NOT: 3, XOR: 1 }, par: 8,
    inputs: ["a1", "a0", "b1", "b0"], outputs: ["LT"],
    tests: buildTests(4, ([a1, a0, b1, b0]) => [(((a1 << 1) | a0) < ((b1 << 1) | b0) ? 1 : 0)]) },
  { id: "eq3", chapter: CH.arith, name: "3-bit Equality", tag: "Compare",
    briefing: "AND three per-bit XNORs (each XOR+NOT); the 3-AND from two 2-ANDs.",
    allowed: { XOR: 3, NOT: 3, AND: 2 }, par: 8,
    inputs: ["a2", "a1", "a0", "b2", "b1", "b0"], outputs: ["EQ"],
    tests: buildTests(6, (v) => [(v.slice(0, 3).join("") === v.slice(3).join("") ? 1 : 0)]) },
  { id: "neg2", chapter: CH.arith, name: "Negate (2-bit)", tag: "Add",
    briefing: "Two's complement of 2 bits: n0=b0 needs just a wire! n1=b1⊕b0. One XOR total.",
    allowed: { XOR: 1 }, par: 1, inputs: ["b1", "b0"], outputs: ["n1", "n0"],
    tests: buildTests(2, ([b1, b0]) => [((b1 ^ b0)), b0]) },
  { id: "cla1", chapter: CH.arith, name: "Carry Lookahead Bit", tag: "Add",
    briefing: "C1=(A∧B)∨((A⊕B)∧C0): generate/propagate, no ripple wait.",
    allowed: { XOR: 1, AND: 2, OR: 1 }, par: 4, inputs: ["A", "B", "C0"], outputs: ["C1"],
    tests: buildTests(3, ([a, b, c0]) => [((a & b) || ((a ^ b) & c0) ? 1 : 0)]) },
  { id: "inc4", chapter: CH.arith, name: "Nibble Incrementer", tag: "Add",
    briefing: "+1 on 4 bits: s0=¬b0, then ripple XOR/AND pairs up the bits.",
    allowed: { XOR: 3, AND: 2, NOT: 1 }, par: 6,
    inputs: ["b3", "b2", "b1", "b0"], outputs: ["s3", "s2", "s1", "s0"],
    tests: buildTests(4, ([b3, b2, b1, b0]) => {
      const s = (((b3 << 3) | (b2 << 2) | (b1 << 1) | b0) + 1) & 15;
      return [(s >> 3) & 1, (s >> 2) & 1, (s >> 1) & 1, s & 1];
    }) },
  { id: "addsub2", chapter: CH.arith, name: "2-bit Subtractor", tag: "Subtract",
    briefing: "Half-subtract bit0, full-subtract bit1 with the borrow chained.",
    allowed: { XOR: 3, AND: 3, NOT: 3, OR: 1 }, par: 10,
    inputs: ["a1", "a0", "b1", "b0"], outputs: ["D1", "D0", "Bout"],
    tests: buildTests(4, ([a1, a0, b1, b0]) => {
      const a = (a1 << 1) | a0, b = (b1 << 1) | b0;
      const d = (a - b + 8) & 3;
      return [(d >> 1) & 1, d & 1, (a < b ? 1 : 0)];
    }) },
  { id: "mul2", chapter: CH.arith, name: "2×2 Multiplier", tag: "Multiply",
    briefing: "Four partial-product ANDs, then a half-adder-style combine for m1..m3.",
    allowed: { AND: 6, XOR: 2 }, par: 8,
    inputs: ["a1", "a0", "b1", "b0"], outputs: ["m3", "m2", "m1", "m0"],
    tests: buildTests(4, ([a1, a0, b1, b0]) => {
      const p = ((a1 << 1) | a0) * ((b1 << 1) | b0);
      return [(p >> 3) & 1, (p >> 2) & 1, (p >> 1) & 1, p & 1];
    }) },
  { id: "add3s", chapter: CH.arith, name: "3-bit Adder (sampled)", tag: "Add",
    briefing: "Ripple HA+FA+FA over 3 bits. 12 gates; 24 hand-picked vectors (full 64 would flood the table).",
    allowed: { AND: 5, OR: 2, XOR: 5 }, par: 12,
    inputs: ["a2", "a1", "a0", "b2", "b1", "b0"], outputs: ["s2", "s1", "s0", "cout"],
    tests: ADD3_VECTORS },

  // ================= H. Codes & detectors (N76–N83) =================
  { id: "gray2", chapter: CH.codes, name: "Gray Code (2-bit)", tag: "Code",
    briefing: "g1=b1 is just a wire; g0=b1⊕b0. One XOR total.",
    allowed: { XOR: 1 }, par: 1, inputs: ["b1", "b0"], outputs: ["g1", "g0"],
    tests: buildTests(2, ([b1, b0]) => [b1, (b1 ^ b0)]) },
  { id: "gray3", chapter: CH.codes, name: "Gray Code (3-bit)", tag: "Code",
    briefing: "g2=b2 (wire), g1=b2⊕b1, g0=b1⊕b0.",
    allowed: { XOR: 2 }, par: 2, inputs: ["b2", "b1", "b0"], outputs: ["g2", "g1", "g0"],
    tests: buildTests(3, ([b2, b1, b0]) => [b2, (b2 ^ b1), (b1 ^ b0)]) },
  { id: "even3", chapter: CH.codes, name: "Evenness of 3 (XOR box)", tag: "Code",
    briefing: "Same function as XNOR3 but only XOR + NOT allowed: 2 XORs + NOT.",
    allowed: { XOR: 2, NOT: 1 }, par: 3, inputs: ["A", "B", "C"], outputs: ["Y"],
    tests: buildTests(3, ([a, b, c]) => [(a ^ b ^ c ? 0 : 1)]) },
  { id: "xnor4chain", chapter: CH.codes, name: "XNOR Chain", tag: "Code",
    briefing: "Cascade three XNORs: ((A⊙B)⊙C)⊙D.",
    allowed: { XNOR: 3 }, par: 3, inputs: ["A", "B", "C", "D"], outputs: ["Y"],
    tests: buildTests(4, ([a, b, c, d]) => {
      const xnor = (p, q) => ((p ^ q) ? 0 : 1);
      return [xnor(xnor(xnor(a, b), c), d)];
    }) },
  { id: "busparity", chapter: CH.codes, name: "Bus Parity", tag: "Code",
    briefing: "Odd parity over a 5-wire bus. Four XORs in a chain.",
    allowed: { XOR: 4 }, par: 4, inputs: ["A", "B", "C", "D", "E"], outputs: ["P"],
    tests: buildTests(5, ([a, b, c, d, e]) => [a ^ b ^ c ^ d ^ e]) },
  { id: "onehot3", chapter: CH.codes, name: "Exactly-One Detector", tag: "Detect",
    briefing: "Y=1 iff exactly one input is 1: parity AND NOT(any pair). 2 XOR + 3 AND + 2 OR + NOT.",
    allowed: { XOR: 2, AND: 4, OR: 2, NOT: 1 }, par: 9, inputs: ["A", "B", "C"], outputs: ["Y"],
    tests: buildTests(3, ([a, b, c]) => [((a ^ b ^ c) && !((a && b) || (a && c) || (b && c)) ? 1 : 0)]) },
  { id: "zero4", chapter: CH.codes, name: "All-Zero Detector", tag: "Detect",
    briefing: "Y=1 iff ABCD=0000: 3-OR tree + output NOT (a 4-NOR).",
    allowed: { OR: 3, NOT: 1 }, par: 4, inputs: ["A", "B", "C", "D"], outputs: ["Y"],
    tests: buildTests(4, ([a, b, c, d]) => [((a || b || c || d) ? 0 : 1)]) },
  { id: "allone4", chapter: CH.codes, name: "All-One Detector", tag: "Detect",
    briefing: "Y=1 iff ABCD=1111: 3-AND tree.",
    allowed: { AND: 3 }, par: 3, inputs: ["A", "B", "C", "D"], outputs: ["Y"],
    tests: buildTests(4, ([a, b, c, d]) => [(a && b && c && d ? 1 : 0)]) },

  // ================= Seven segments (N84–N90) =================
  { id: "seg-a", chapter: CH.seg7, name: "7-seg A", tag: "Display",
    briefing: "Top bar from BCD wxyz: on for digits {0,2,3,5,6,7,8,9}. K-map it: A=¬x∧¬z ∨ y ∨ x∧z ∨ w.",
    allowed: { NOT: 2, AND: 2, OR: 3 }, par: 7, inputs: ["w", "x", "y", "z"], outputs: ["A"],
    cover: SEG_COVER.a, tests: segEntry("a") },
  { id: "seg-b", chapter: CH.seg7, name: "7-seg B", tag: "Display",
    briefing: "Upper-right bar: on for {0,1,2,3,4,7,8,9}. B=¬x ∨ ¬y∧¬z ∨ y∧z.",
    allowed: { NOT: 3, AND: 2, OR: 2 }, par: 7, inputs: ["w", "x", "y", "z"], outputs: ["B"],
    cover: SEG_COVER.b, tests: segEntry("b") },
  { id: "seg-c", chapter: CH.seg7, name: "7-seg C", tag: "Display",
    briefing: "Lower-right bar: on for everything except 2. C=¬y ∨ z ∨ x.",
    allowed: { NOT: 1, OR: 2 }, par: 3, inputs: ["w", "x", "y", "z"], outputs: ["C"],
    cover: SEG_COVER.c, tests: segEntry("c") },
  { id: "seg-d", chapter: CH.seg7, name: "7-seg D", tag: "Display",
    briefing: "Bottom bar: on for {0,2,3,5,6,8,9}. Five product terms — the beast of the set.",
    allowed: { NOT: 3, AND: 5, OR: 4 }, par: 12, inputs: ["w", "x", "y", "z"], outputs: ["D"],
    cover: SEG_COVER.d, tests: segEntry("d") },
  { id: "seg-e", chapter: CH.seg7, name: "7-seg E", tag: "Display",
    briefing: "Lower-left bar: on for {0,2,6,8}. E=(¬x∧¬z) ∨ (y∧¬z).",
    allowed: { NOT: 2, AND: 2, OR: 1 }, par: 5, inputs: ["w", "x", "y", "z"], outputs: ["E"],
    cover: SEG_COVER.e, tests: segEntry("e") },
  { id: "seg-f", chapter: CH.seg7, name: "7-seg F", tag: "Display",
    briefing: "Upper-left bar: on for {0,4,5,6,8,9}.",
    allowed: { NOT: 2, AND: 3, OR: 3 }, par: 8, inputs: ["w", "x", "y", "z"], outputs: ["F"],
    cover: SEG_COVER.f, tests: segEntry("f") },
  { id: "seg-g", chapter: CH.seg7, name: "7-seg G", tag: "Display",
    briefing: "Middle bar: on for {2,3,4,5,6,8,9}.",
    allowed: { NOT: 3, AND: 3, OR: 3 }, par: 9, inputs: ["w", "x", "y", "z"], outputs: ["G"],
    cover: SEG_COVER.g, tests: segEntry("g") },

  // ================= I. Debug ward (N91–N100) =================
  { id: "dbg-not", chapter: CH.debug, name: "Broken Inverter", tag: "Debug",
    briefing: "The input is wired but the lamp stays dark — the NOT output goes nowhere. Finish the job: wire NOT → Y.",
    allowed: { NOT: 1 }, par: 1, inputs: ["A"], outputs: ["Y"],
    tests: buildTests(1, ([a]) => [a ? 0 : 1]),
    prefill: { nodes: [{ key: "g0", type: "NOT", x: 434, y: 244 }],
      wires: [{ from: "in0", to: "g0", toPin: 0 }] } },
  { id: "dbg-swap", chapter: CH.debug, name: "AND/OR Swap", tag: "Debug",
    briefing: "The task needs OR but an AND sits on the bench, fully wired. Swap the gate.",
    allowed: { OR: 1 }, par: 1, inputs: ["A", "B"], outputs: ["Y"],
    tests: buildTests(2, ([a, b]) => [a | b]),
    prefill: { nodes: [{ key: "g0", type: "AND", x: 434, y: 236 }],
      wires: [{ from: "in0", to: "g0", toPin: 0 }, { from: "in1", to: "g0", toPin: 1 }, { from: "g0", to: "out0", toPin: 0 }] } },
  { id: "dbg-notmiss", chapter: CH.debug, name: "Missing Inverters", tag: "Debug",
    briefing: "This XOR attempt feeds A,B straight into the ANDs — the two NOTs are missing. Add and rewire.",
    allowed: { AND: 4, OR: 2, NOT: 4 }, par: 5, inputs: ["A", "B"], outputs: ["Y"],
    tests: buildTests(2, ([a, b]) => [a ^ b]),
    prefill: { nodes: [
        { key: "g0", type: "AND", x: 330, y: 170 }, { key: "g1", type: "AND", x: 330, y: 320 },
        { key: "g2", type: "OR", x: 560, y: 245 }],
      wires: [{ from: "in0", to: "g0", toPin: 0 }, { from: "in1", to: "g0", toPin: 1 },
        { from: "in0", to: "g1", toPin: 0 }, { from: "in1", to: "g1", toPin: 1 },
        { from: "g0", to: "g2", toPin: 0 }, { from: "g1", to: "g2", toPin: 1 },
        { from: "g2", to: "out0", toPin: 0 }] } },
  { id: "dbg-tied", chapter: CH.debug, name: "Tied Inputs", tag: "Debug",
    briefing: "Both AND inputs are fed by A; B dangles. Move one wire to B.",
    allowed: { AND: 1 }, par: 1, inputs: ["A", "B"], outputs: ["Y"],
    tests: buildTests(2, ([a, b]) => [a & b]),
    prefill: { nodes: [{ key: "g0", type: "AND", x: 434, y: 236 }],
      wires: [{ from: "in0", to: "g0", toPin: 0 }, { from: "in0", to: "g0", toPin: 1 }, { from: "g0", to: "out0", toPin: 0 }] } },
  { id: "dbg-carry", chapter: CH.debug, name: "Swapped Sum/Carry", tag: "Debug",
    briefing: "Half adder gates are right but S and C outputs are crossed. Swap two wires.",
    allowed: { AND: 2, OR: 2, NOT: 2, XOR: 2 }, par: 2, inputs: ["A", "B"], outputs: ["S", "C"],
    tests: buildTests(2, ([a, b]) => [a ^ b, a & b]),
    prefill: { nodes: [{ key: "g0", type: "XOR", x: 434, y: 140 }, { key: "g1", type: "AND", x: 434, y: 330 }],
      wires: [{ from: "in0", to: "g0", toPin: 0 }, { from: "in1", to: "g0", toPin: 1 },
        { from: "in0", to: "g1", toPin: 0 }, { from: "in1", to: "g1", toPin: 1 },
        { from: "g0", to: "out1", toPin: 0 }, { from: "g1", to: "out0", toPin: 0 }] } },
  { id: "dbg-nandx", chapter: CH.debug, name: "NAND-XOR Fault", tag: "Debug",
    briefing: "One NAND in the XOR is fed B,B instead of B,D. Find it, move one wire.",
    allowed: { NAND: 4 }, par: 4, inputs: ["A", "B"], outputs: ["Y"],
    tests: buildTests(2, ([a, b]) => [a ^ b]),
    prefill: { nodes: [
        { key: "g0", type: "NAND", x: 260, y: 120 }, { key: "g1", type: "NAND", x: 260, y: 360 },
        { key: "g2", type: "NAND", x: 470, y: 120 }, { key: "g3", type: "NAND", x: 660, y: 240 }],
      wires: [{ from: "in0", to: "g0", toPin: 0 }, { from: "in1", to: "g0", toPin: 1 },
        { from: "in0", to: "g1", toPin: 0 }, { from: "g0", to: "g1", toPin: 1 },
        { from: "in1", to: "g2", toPin: 0 }, { from: "in1", to: "g2", toPin: 1 },
        { from: "g1", to: "g3", toPin: 0 }, { from: "g2", to: "g3", toPin: 1 },
        { from: "g3", to: "out0", toPin: 0 }] } },
  { id: "dbg-maj", chapter: CH.debug, name: "Missing Term", tag: "Debug",
    briefing: "Majority is missing its B∧C term (only two ANDs + ORs). Add the term.",
    allowed: { AND: 4, OR: 3, NOT: 2 }, par: 5, inputs: ["A", "B", "C"], outputs: ["Y"],
    tests: buildTests(3, ([a, b, c]) => [(a + b + c >= 2 ? 1 : 0)]),
    prefill: { nodes: [
        { key: "g0", type: "AND", x: 280, y: 110 }, { key: "g1", type: "AND", x: 280, y: 320 },
        { key: "g2", type: "OR", x: 490, y: 210 }, { key: "g3", type: "OR", x: 680, y: 210 }],
      wires: [{ from: "in0", to: "g0", toPin: 0 }, { from: "in1", to: "g0", toPin: 1 },
        { from: "in0", to: "g1", toPin: 0 }, { from: "in2", to: "g1", toPin: 1 },
        { from: "g0", to: "g2", toPin: 0 }, { from: "g1", to: "g2", toPin: 1 },
        { from: "g2", to: "g3", toPin: 0 }, { from: "g3", to: "out0", toPin: 0 }] } },
  { id: "dbg-muxsel", chapter: CH.debug, name: "Inverted Select", tag: "Debug",
    briefing: "This MUX picks B when S=0 — the select legs are swapped. Swap two wires.",
    allowed: { AND: 4, OR: 2, NOT: 2 }, par: 4, inputs: ["A", "B", "S"], outputs: ["Y"],
    tests: buildTests(3, ([a, b, s]) => [(s ? b : a)]),
    prefill: { nodes: [
        { key: "g0", type: "NOT", x: 280, y: 244 }, { key: "g1", type: "AND", x: 470, y: 140 },
        { key: "g2", type: "AND", x: 470, y: 340 }, { key: "g3", type: "OR", x: 660, y: 240 }],
      wires: [{ from: "in2", to: "g0", toPin: 0 },
        { from: "in2", to: "g1", toPin: 0 }, { from: "in0", to: "g1", toPin: 1 },
        { from: "g0", to: "g2", toPin: 0 }, { from: "in1", to: "g2", toPin: 1 },
        { from: "g1", to: "g3", toPin: 0 }, { from: "g2", to: "g3", toPin: 1 },
        { from: "g3", to: "out0", toPin: 0 }] } },
  { id: "dbg-dec", chapter: CH.debug, name: "Decoder Typo", tag: "Debug",
    briefing: "Y2 lights for 01 instead of 10 — one minterm uses ¬A instead of A. Move one wire.",
    allowed: { AND: 4, NOT: 2 }, par: 6, inputs: ["A", "B"], outputs: ["Y0", "Y1", "Y2", "Y3"],
    tests: buildTests(2, ([a, b]) => [
      ((!a && !b) ? 1 : 0), ((!a && b) ? 1 : 0), ((a && !b) ? 1 : 0), ((a && b) ? 1 : 0),
    ]),
    prefill: { nodes: [
        { key: "g0", type: "NOT", x: 170, y: 80 }, { key: "g1", type: "NOT", x: 170, y: 300 },
        { key: "g2", type: "AND", x: 400, y: 50 }, { key: "g3", type: "AND", x: 400, y: 180 },
        { key: "g4", type: "AND", x: 400, y: 310 }, { key: "g5", type: "AND", x: 400, y: 440 }],
      wires: [{ from: "in0", to: "g0", toPin: 0 }, { from: "in1", to: "g1", toPin: 0 },
        { from: "g0", to: "g2", toPin: 0 }, { from: "g1", to: "g2", toPin: 1 },
        { from: "g0", to: "g3", toPin: 0 }, { from: "in1", to: "g3", toPin: 1 },
        { from: "g0", to: "g4", toPin: 0 }, { from: "g1", to: "g4", toPin: 1 },
        { from: "in0", to: "g5", toPin: 0 }, { from: "in1", to: "g5", toPin: 1 },
        { from: "g2", to: "out0", toPin: 0 }, { from: "g3", to: "out1", toPin: 0 },
        { from: "g4", to: "out2", toPin: 0 }, { from: "g5", to: "out3", toPin: 0 }] } },
  { id: "dbg-par", chapter: CH.debug, name: "Flipped Parity", tag: "Debug",
    briefing: "The XOR chain is right but a stray NOT flips the answer. Delete it and rewire.",
    allowed: { XOR: 3 }, par: 3, inputs: ["A", "B", "C", "D"], outputs: ["P"],
    tests: buildTests(4, ([a, b, c, d]) => [a ^ b ^ c ^ d]),
    prefill: { nodes: [
        { key: "g0", type: "XOR", x: 250, y: 236 }, { key: "g1", type: "XOR", x: 420, y: 236 },
        { key: "g2", type: "XOR", x: 590, y: 236 }, { key: "g3", type: "NOT", x: 740, y: 244 }],
      wires: [{ from: "in0", to: "g0", toPin: 0 }, { from: "in1", to: "g0", toPin: 1 },
        { from: "g0", to: "g1", toPin: 0 }, { from: "in2", to: "g1", toPin: 1 },
        { from: "g1", to: "g2", toPin: 0 }, { from: "in3", to: "g2", toPin: 1 },
        { from: "g2", to: "g3", toPin: 0 }, { from: "g3", to: "out0", toPin: 0 }] } },
];
